### ISSUE TITLE
Support additional operating systems.

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/ansible-galaxy-os#1]
Explicit support and tests (maybe `Dockerfiles` for each) for wide range of operating systems.
- [ ] CentOS 6
- [x] CentOS 7
- [ ] Scientific Linux 7
- [ ] Debian Wheezy
- [ ] Ubuntu 14.10

**Comment by MatthewRalston** [comment]
That would be so nice...

**Comment by afgane** [comment]
Effectively and realistically completed with PR #24.
